{
  "formatVersion": "1.1",
  "component": {
    "group": "com.andreidurlea",
    "module": "corecontrol",
    "version": "1.0.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.0.0-alpha.aar",
          "url": "corecontrol-1.0.0-alpha.aar",
          "size": 121492,
          "sha512": "e3a6c3ebcb49f86c375a0ba687d19ab521308510ddacbb36d8cf72ad47d6e67a256e6a03cdb2cba54a02033c02606bae3be0ff7268b5f700b309983617faf57c",
          "sha256": "5ac4da7bc8328cb36fd1a68d98e6d211e5a4a55466213f0e8baafc0722091280",
          "sha1": "ae59c6c2d9bd58213e16672329e4853ca92d1093",
          "md5": "892f52d2b78e28f90765ad8270423489"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Inspection",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Blocks",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotServer",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "OnBotJava",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "FtcCommon",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "Vision",
          "version": {
            "requires": "11.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "corecontrol-1.0.0-alpha.aar",
          "url": "corecontrol-1.0.0-alpha.aar",
          "size": 121492,
          "sha512": "e3a6c3ebcb49f86c375a0ba687d19ab521308510ddacbb36d8cf72ad47d6e67a256e6a03cdb2cba54a02033c02606bae3be0ff7268b5f700b309983617faf57c",
          "sha256": "5ac4da7bc8328cb36fd1a68d98e6d211e5a4a55466213f0e8baafc0722091280",
          "sha1": "ae59c6c2d9bd58213e16672329e4853ca92d1093",
          "md5": "892f52d2b78e28f90765ad8270423489"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "corecontrol-1.0.0-alpha-sources.jar",
          "url": "corecontrol-1.0.0-alpha-sources.jar",
          "size": 78111,
          "sha512": "168b1618a7c8e5a01eb6697ad0c6ec282065c1da78825ae9ac82084c2728319b392c37023bcb507fd372dd548c3db33d855544a141768b291fee7efe16957ecf",
          "sha256": "4f944a28daa09943f375f1c5aaef2784c134df1d5c1244051a5e8c268bfa169e",
          "sha1": "1fd91ec77ad3b24c2b0a5ab0958b4b4cc3242579",
          "md5": "ce64975aa8881f023530a9e855fbcb0a"
        }
      ]
    }
  ]
}
